# Generated by Django 3.2.6 on 2021-10-13 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='up_date',
            new_name='PublishDate',
        ),
    ]
