# Generated by Django 3.2.6 on 2021-10-24 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20211022_2333'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=50)),
                ('banner_text', models.CharField(max_length=80)),
                ('btn_text', models.CharField(max_length=20)),
                ('cover_image', models.ImageField(default='', upload_to='shop/CoverImages')),
            ],
        ),
    ]
