# Generated by Django 3.2.8 on 2021-11-25 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_homebanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(max_length=50)),
                ('percentage', models.IntegerField(default=0)),
                ('cover_image', models.ImageField(upload_to='shop/images/SalesImage')),
            ],
        ),
        migrations.AlterField(
            model_name='homebanner',
            name='cover_image',
            field=models.ImageField(default='', upload_to='shop/images/CoverImages'),
        ),
    ]
