# Generated by Django 3.2.8 on 2021-11-25 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20211125_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='cover_image',
            field=models.ImageField(default='', upload_to='shop/images/SalesImage'),
        ),
    ]
