# Generated by Django 3.2.8 on 2021-11-26 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_rename_sales_sale'),
    ]

    operations = [
        migrations.CreateModel(
            name='Featured',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(max_length=50)),
                ('discount_price', models.IntegerField(default=0)),
                ('main_price', models.IntegerField(default=0)),
                ('cover_image', models.ImageField(default='', upload_to='shop/images/FeaturedImage')),
            ],
        ),
    ]
