# Generated by Django 3.2.8 on 2021-11-30 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_featured_cover_image_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='homebanner',
            name='percentage',
            field=models.IntegerField(default=0),
        ),
    ]
