# Generated by Django 3.2.8 on 2021-11-30 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_homebanner_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homebanner',
            name='percentage',
        ),
    ]
