# Generated by Django 3.2.8 on 2021-12-07 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_remove_homebanner_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='SubCategory',
        ),
        migrations.AlterField(
            model_name='featured',
            name='ProductName',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='productImage',
            field=models.ImageField(default='', upload_to='shop/images/AllProducts'),
        ),
    ]
