# Generated by Django 3.2.8 on 2022-01-17 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_product_stars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stars',
        ),
        migrations.AddField(
            model_name='product',
            name='Ratings 1 - 10',
            field=models.IntegerField(default=0, max_length=10),
        ),
    ]
