# Generated by Django 3.2.8 on 2022-01-23 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20220117_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Ratings 1 - 10',
        ),
        migrations.AddField(
            model_name='product',
            name='Ratings',
            field=models.IntegerField(default=0),
        ),
    ]
