# Generated by Django 3.2.8 on 2022-01-23 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20220123_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Ratings(25, 50, 75, 100)',
        ),
        migrations.AddField(
            model_name='product',
            name='Ratings',
            field=models.IntegerField(default=0, verbose_name='Ratings(25, 50, 75, 100)'),
        ),
    ]
