# Generated by Django 3.2.8 on 2022-01-27 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_featured_ratings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='featured',
            old_name='discount_price',
            new_name='price_before',
        ),
        migrations.RenameField(
            model_name='featured',
            old_name='main_price',
            new_name='price_now',
        ),
    ]
