# Generated by Django 3.2.8 on 2022-01-29 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_auto_20220127_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='featured',
            name='category',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=150),
        ),
    ]
